# Generated by Django 4.1.6 on 2023-02-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('duracao', models.IntegerField()),
                ('descricao', models.CharField(max_length=150)),
                ('numero_credito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
                ('redes', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
                ('redes', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=500, null=True)),
                ('descricao', models.TextField(null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.TextField(max_length=20000, null=True)),
            ],
        ),
    ]
