# Generated by Django 4.1.4 on 2023-02-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagem',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='imagem',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
