# Generated by Django 4.1.4 on 2023-01-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0002_login_remove_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='login',
            new_name='email',
        ),
    ]
