# Generated by Django 4.1.4 on 2023-01-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
                ('redes', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
