# Generated by Django 4.1.6 on 2023-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0005_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
