# Generated by Django 4.1.6 on 2023-02-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0006_alter_noticia_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
                ('redes', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
