# Generated by Django 4.1.3 on 2023-02-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0007_empresa_alter_noticia_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
