# Generated by Django 4.1.3 on 2023-02-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fga', '0009_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
